# fuzzel.ini
# Wallust-derived colors (MyDark.jpg)

font=Iosevka Custom:weight=bold:size=12
line-height=25
fields=name,generic,comment,categories,filename,keywords
terminal=kitty -e
prompt="❯   " 
layer=overlay
lines=15

[colors]
background=1C181Faa
text=ffffffff
match=854D78ff
selection=433E47ff
selection-match=854D78ff
selection-text=ffffffff
border=854D78ff

[border]
radius=4
width=3
