# fnott.ini
# Styles derived from fuzzel.ini

# Default values
font=Iosevka Custom:weight=bold:size=14
background=1e1e2eaa
border-color=b4befeff
border-width=2
border-radius=4

# Text colors
title-color=cdd6f4ff
summary-color=cdd6f4ff
body-color=cdd6f4ff

# Progress bar colors
progress-bar-color=f38ba8ff

[low]
background=1e1e2eaa
title-color=cdd6f4ff
summary-color=cdd6f4ff
body-color=cdd6f4ff

[normal]
background=1e1e2eaa
title-color=cdd6f4ff
summary-color=cdd6f4ff
body-color=cdd6f4ff

[critical]
background=1e1e2eaa
border-color=f38ba8ff
title-color=f38ba8ff
summary-color=f38ba8ff
body-color=f38ba8ff
