-- Generated by nwg-displays on 2026-08-10 at 14:03:23. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2400@60.0",
    position = "0x0",
    scale = 1.5000000000000004,
    bitdepth = 10
})
