# fnott.ini
# Styles derived from wallust (MyDark.jpg)

[main]
background=000000aa
border-color=854D78ff
border-size=2
border-radius=4
default-timeout=30

# Default Text colors (White for readability)
title-color=ffffffff
summary-color=ffffffff
body-color=ffffffff

# Progress bar colors (using primary accent)
progress-color=854D78ff

[low]
default-timeout=8
title-font=Iosevka Custom:weight=bold:size=10
summary-font=Iosevka Custom:weight=bold:size=10
body-font=Iosevka Custom:weight=bold:size=9
background=000000aa
border-color=433E47aa
title-color=a6adc8ff
summary-color=a6adc8ff
body-color=a6adc8ff

[normal]
default-timeout=21
title-font=Iosevka Custom:weight=bold:size=11
summary-font=Iosevka Custom:weight=bold:size=11
body-font=Iosevka Custom:weight=bold:size=10
background=000000aa
border-color=854D78ff

[critical]
default-timeout=55
title-font=Iosevka Custom:weight=bold:size=12
summary-font=Iosevka Custom:weight=bold:size=12
body-font=Iosevka Custom:weight=bold:size=11
background=28000055
border-color=b10000ff
title-color=f38ba8ff
summary-color=f38ba8ff
body-color=f38ba8ff
