# Window and Workspace Rules
# Placeholder for now

windowrule = match:xwayland on, float on

# Floating Shell / Calculator
windowrule = match:class (floating_shell), float 1
windowrule = match:class (floating_shell), size 600 400
windowrule = match:class (floating_shell), center 1
